const CATEGORIES = [
  { id: 'todos', label: 'Todos' },
  { id: 'antibioticos', label: 'Antibióticos' },
  { id: 'analgesicos', label: 'Analgésicos' },
  { id: 'vitaminas', label: 'Vitaminas y Suplementos' },
  { id: 'cardiovascular', label: 'Cardiovascular' },
  { id: 'antifungicos', label: 'Antifúngicos' },
  { id: 'gastrointestinal', label: 'Gastrointestinal' },
  { id: 'neurologico', label: 'Sistema Nervioso' },
  { id: 'dermatologico', label: 'Dermatológicos' },
  { id: 'otros', label: 'Otros' },
];

const PRODUCTS = [
  // ── ANTIBIÓTICOS ──
  { id: 1,  name: 'Amoxicilina Cápsulas BP 100 mg',              category: 'antibioticos',    img: 'assects/Amoxicilina 100 mg.png' },
  { id: 2,  name: 'Amoxicilina Cápsulas BP 500 mg',              category: 'antibioticos',    img: 'assects/Amoxicilina 500 mg.png' },
  { id: 3,  name: 'Amoxicilina Cápsulas BP 1000 mg',             category: 'antibioticos',    img: 'assects/Amoxicilina 1000.png' },
  { id: 4,  name: 'Amoxicilina Suspensión Oral BP 250 mg',       category: 'antibioticos',    img: 'assects/Amoxicilina suspension.png' },
  { id: 5,  name: 'Ampicilina Cápsulas BP 500 mg',               category: 'antibioticos',    img: 'assects/Ampicilina 500 mg.png' },
  { id: 6,  name: 'Ampicilina Tabletas 1000 mg',                 category: 'antibioticos',    img: 'assects/Ampicilina 1000 mg.png' },
  { id: 7,  name: 'Ampicilina Tabletas',                         category: 'antibioticos',    img: 'assects/Ampicilina.png' },
  { id: 8,  name: 'Azitromicina Tabletas USP 500 mg',            category: 'antibioticos',    img: 'assects/Azitromicina 500 mg.png' },
  { id: 9,  name: 'Azitromicina Tabletas USP 500 mg (Grande)',   category: 'antibioticos',    img: 'assects/Azitromicina grande.png' },
  { id: 10, name: 'Azitromicina Tabletas USP 500 mg (Pequeña)',  category: 'antibioticos',    img: 'assects/Azitromicina.png' },
  { id: 11, name: 'Cefalexin Cápsulas BP 500 mg',                category: 'antibioticos',    img: 'assects/Cefalexin.png' },
  { id: 12, name: 'Ceftriaxona Para Inyección USP 1 g',          category: 'antibioticos',    img: 'assects/Ceftriazona.png' },
  { id: 13, name: 'Ciprofloxacin Tabletas USP 500 mg',           category: 'antibioticos',    img: 'assects/Ciprofloxacin.png' },
  { id: 14, name: 'Claritromicina Tabletas USP 500 mg',          category: 'antibioticos',    img: 'assects/Claritromicina 500 mg.png' },
  { id: 15, name: 'Claritromicina Tabletas USP 500 mg (Caja)',   category: 'antibioticos',    img: 'assects/Claritromicina.png' },
  { id: 16, name: 'Clindamicina Cápsulas BP 300 mg',             category: 'antibioticos',    img: 'assects/Clindamicina.png' },
  { id: 17, name: 'Cloxacilina Sódica Cápsulas USP 500 mg',     category: 'antibioticos',    img: 'assects/Cloxacilina 500 mg.png' },
  { id: 18, name: 'Doxiciclina Cápsulas BP 100 mg',              category: 'antibioticos',    img: 'assects/Doxiciclina Capsulas 100 mg.png' },
  { id: 19, name: 'Doxiciclina Cápsulas 100 mg',                 category: 'antibioticos',    img: 'assects/Doxiciclina.png' },
  { id: 20, name: 'Eritromicina Estearato Tabletas BP 500 mg',   category: 'antibioticos',    img: 'assects/Eritromicina 500mg.png' },
  { id: 21, name: 'Eritromicina Estolato Suspensión Oral 250 mg',category: 'antibioticos',    img: 'assects/Eritromicina Estolato.png' },
  { id: 22, name: 'Levofloxacina 500 mg Tabletas',               category: 'antibioticos',    img: 'assects/Levofloxacina.png' },
  // Nota: archivo "Lincomycin.png" contiene Acetaminofén 750 mg (ver analgesicos, id 36)
  { id: 23, name: 'Lincomicina Cápsulas BP 500 mg',              category: 'antibioticos',    img: 'assects/Acetaminofen 750.png' },
  { id: 24, name: 'Penicilina Benzatínica Fortificada Triple',   category: 'antibioticos',    img: 'assects/Penicilina benzatinica fortificada triple.png' },
  { id: 25, name: 'Fosfomicina Tabletas 500 mg',                 category: 'antibioticos',    img: 'assects/Fosfomycin.png' },

  // ── ANALGÉSICOS / ANTIINFLAMATORIOS ──
  { id: 31, name: 'Acetaminofén Tabletas USP 500 mg',            category: 'analgesicos',     img: 'assects/Acetaminophen 500 mg.png' },
  // Archivo "Lincomycin.png" contiene Acetaminofén 750 mg
  { id: 36, name: 'Acetaminofén Tabletas USP 750 mg',            category: 'analgesicos',     img: 'assects/Lincomycin.png' },
  { id: 32, name: 'Ácido Mefenámico Tabletas BP 500 mg',         category: 'analgesicos',     img: 'assects/Acido Mefenamico.png' },
  { id: 33, name: 'Celecoxib Cápsulas 200 mg',                   category: 'analgesicos',     img: 'assects/Celecoxib.png' },
  { id: 34, name: 'Diclofenac Gel',                              category: 'analgesicos',     img: 'assects/Diclofenac gel.png' },
  { id: 35, name: 'Diclofenac Potásico Tabletas',                category: 'analgesicos',     img: 'assects/Diclofenac potasico.png' },
  { id: 37, name: 'Diclofenac Sódico 100 mg',                    category: 'analgesicos',     img: 'assects/Diclofenac Sodico 100 mg.png' },
  { id: 38, name: 'Diclofenac Sódico Tabletas',                  category: 'analgesicos',     img: 'assects/Diclofenac Sodico.png' },
  { id: 39, name: 'Diclofenaco 75 mg',                           category: 'analgesicos',     img: 'assects/Diclofenaco 75mg.png' },
  { id: 40, name: 'Dolocom Grande',                              category: 'analgesicos',     img: 'assects/Dolocom grande.png' },
  { id: 41, name: 'Dolocom Pequeño',                             category: 'analgesicos',     img: 'assects/Dolocom pequeño.png' },
  { id: 42, name: 'Dolocom',                                     category: 'analgesicos',     img: 'assects/Dolocom Saad.png' },
  { id: 43, name: 'Ibuprofen Tabletas',                          category: 'analgesicos',     img: 'assects/Ibuprofeno.png' },
  { id: 44, name: 'Ibuprofen Suspensión Oral 100 mg/5ml',        category: 'analgesicos',     img: 'assects/Ibuprofeno suspension.png' },
  { id: 45, name: 'Paracetamol + Diclofenac Tabletas (Satro Plus)', category: 'analgesicos', img: 'assects/Paracetamol + Diclofenac.png' },
  { id: 130,name: 'Micsa-15 (Meloxicam Tabletas BP 15 mg)',      category: 'analgesicos',     img: 'assects/Micsa - 15.png' },

  // ── VITAMINAS Y SUPLEMENTOS ──
  { id: 46, name: 'Aceite de Linaza 450 mg',                     category: 'vitaminas',       img: 'assects/Aceite de Linaza.png' },
  { id: 47, name: 'Ácido Fólico Tabletas BP 5 mg',               category: 'vitaminas',       img: 'assects/Acido Folico.png' },
  // Archivo "Amoxicilina capsulas 100 mg.png" contiene Vitamina A
  { id: 48, name: 'Vitamina A 50,000 U.I. Perlas',               category: 'vitaminas',       img: 'assects/Amoxicilina capsulas 100 mg.png' },
  { id: 49, name: 'Calcio Carbonato + Vitamina D3',              category: 'vitaminas',       img: 'assects/Calcio + D3.png' },
  { id: 50, name: 'Coenzima Q10 100 mg',                         category: 'vitaminas',       img: 'assects/Coenzima Q10.png' },
  { id: 51, name: 'Colágeno 100 mg Cápsulas',                    category: 'vitaminas',       img: 'assects/Colageno.png' },
  { id: 52, name: 'Colágeno 380 mg + Ácido Hialurónico 100 mg', category: 'vitaminas',       img: 'assects/Colageno Acido Hialuronico.png' },
  { id: 53, name: 'Colágeno Hidrolizado 475 mg + Biotina 5000 mcg', category: 'vitaminas',   img: 'assects/Colageno Hidrolizado + Biotina.png' },
  { id: 54, name: 'Colágeno Hidrolizado 500 mg + Vitamina C 50 mg', category: 'vitaminas',   img: 'assects/Colageno Hidrolizado + vitamina C.png' },
  { id: 55, name: 'Colágeno Hidrolizado 400 mg + Vitamina D3',   category: 'vitaminas',       img: 'assects/Colageno Hidrolizado + Vitamina D3.png' },
  { id: 56, name: 'Complejo B',                                   category: 'vitaminas',       img: 'assects/Complejo B.png' },
  { id: 57, name: 'Espirulina 500 mg',                           category: 'vitaminas',       img: 'assects/Espirulina 500 mg.png' },
  { id: 58, name: 'Melatonina 1 mg',                             category: 'vitaminas',       img: 'assects/Melatonina.png' },
  { id: 59, name: 'Multivitamínico 820 mg',                      category: 'vitaminas',       img: 'assects/Multivitaminico.png' },
  { id: 60, name: 'Multivitamínico Complejo-B Tabletas',         category: 'vitaminas',       img: 'assects/Multivitaminico complejo B.png' },
  { id: 61, name: 'Omega-3 1000 mg',                             category: 'vitaminas',       img: 'assects/Omega 3.png' },
  // Archivo "Vitamina 1000.png" contiene Vitamina E U.I. 1000
  { id: 62, name: 'Vitamina E U.I. 1000 Antioxidante Perlas',   category: 'vitaminas',       img: 'assects/Vitamina 1000.png' },
  { id: 63, name: 'Vitamina C 500 mg',                           category: 'vitaminas',       img: 'assects/Vitamina C.png' },
  { id: 64, name: 'Vitamina C Tabletas Masticables',             category: 'vitaminas',       img: 'assects/Vitamina C Tableta.png' },
  { id: 65, name: 'Vitamina D3 400 UI / 10 mcg',                category: 'vitaminas',       img: 'assects/Vitamina D3.png' },
  { id: 66, name: 'Vitamina E U.I. 400 Antioxidante Perlas',    category: 'vitaminas',       img: 'assects/Vitamina E 400.png' },
  { id: 67, name: 'Vitamina K2 0.1 mg',                         category: 'vitaminas',       img: 'assects/Vitamina K2.png' },
  { id: 68, name: 'Citrato de Magnesio 150 mg',                  category: 'vitaminas',       img: 'assects/Citrato de Magnesio.png' },
  { id: 69, name: 'Citrato de Potasio 100 mg',                   category: 'vitaminas',       img: 'assects/Citrato de potasio.png' },
  { id: 70, name: 'Glicinato de Magnesio 200 mg',               category: 'vitaminas',       img: 'assects/Glicinato de magnesio.png' },
  { id: 71, name: 'Gluconato de Magnesio 500 mg',               category: 'vitaminas',       img: 'assects/Gluconato de Magnesio.png' },
  { id: 72, name: 'Óxido de Magnesio 400 mg',                   category: 'vitaminas',       img: 'assects/Oxido de magnesio 400 mg.png' },
  { id: 73, name: 'Óxido de Magnesio 475 mg',                   category: 'vitaminas',       img: 'assects/Oxido de magnesio 475 mg.png' },
  { id: 74, name: 'Mecobalamina Tabletas 0.5 mg',               category: 'vitaminas',       img: 'assects/Mecobalamina.png' },
  { id: 75, name: 'Sulfato Ferroso 300 mg Tabletas Recubiertas', category: 'vitaminas',       img: 'assects/Sulfato Ferroso.png' },
  // SAFLOX = suplementos vitamina A y D
  { id: 76, name: 'SAFLOX-D Perlas Vitamina A y D (100x10)',    category: 'vitaminas',       img: 'assects/Saflox de 1000.png' },
  { id: 77, name: 'SAFLOX Emulsión Aceite Hígado de Bacalao',   category: 'vitaminas',       img: 'assects/Saflox Emulsion.png' },
  { id: 78, name: 'SAFLOX-D Perlas Vitamina A y D (Frasco Grande)', category: 'vitaminas',  img: 'assects/Saflox grande.png' },
  { id: 79, name: 'SAFLOX-D Perlas Vitamina A y D (Frasco Pequeño)', category: 'vitaminas', img: 'assects/Saflox pequeño.png' },

  // ── CARDIOVASCULAR ──
  { id: 80, name: 'Atenolol Tabletas BP 100 mg',                 category: 'cardiovascular',  img: 'assects/Atenolol.png' },
  { id: 81, name: 'Atenolol Tabletas BP 50 mg',                  category: 'cardiovascular',  img: 'assects/Atenolol 50 mg.png' },
  { id: 82, name: 'Candesartán Cilexetila Tabletas 16 mg',       category: 'cardiovascular',  img: 'assects/Candesartan cilexetila 16 mg.png' },
  { id: 83, name: 'Candesartán Cilexetila Tabletas 8 mg',        category: 'cardiovascular',  img: 'assects/Candesartan cilexetila 8 mg.png' },
  { id: 84, name: 'Captopril Tabletas BP 50 mg',                 category: 'cardiovascular',  img: 'assects/Captopril.png' },
  { id: 85, name: 'Clopidogrel Tabletas USP 75 mg (SAGREL)',     category: 'cardiovascular',  img: 'assects/Clopidogrel Tableta.png' },
  { id: 86, name: 'Digoxin Tablets BP 0.25 mg',                  category: 'cardiovascular',  img: 'assects/Digoxin.png' },
  { id: 87, name: 'Enalapril Maleato 10 mg Tabletas',            category: 'cardiovascular',  img: 'assects/Enalapril Maleato.png' },
  { id: 88, name: 'Hidroclorotiazida Tablets 25 mg',             category: 'cardiovascular',  img: 'assects/Hydrochlorothiazide.png' },
  { id: 89, name: 'Losartán Potásico Tabletas BP 50 mg',         category: 'cardiovascular',  img: 'assects/Losartan potasico.png' },
  { id: 90, name: 'Losartán Potásico Tablets BP 100 mg',         category: 'cardiovascular',  img: 'assects/Lorsatan potasico.png' },
  { id: 91, name: 'Nifedipina 20 mg Tabletas',                   category: 'cardiovascular',  img: 'assects/Nifedipina 20 mg.png' },
  { id: 92, name: 'Rosuvastatina Tabletas 20 mg',                category: 'cardiovascular',  img: 'assects/Rosuvastatina.png' },
  { id: 93, name: 'Rosuvastatina Tableta 10 mg',                 category: 'cardiovascular',  img: 'assects/Rosuvastatina Tableta 10mg.png' },

  // ── ANTIFÚNGICOS ──
  { id: 94, name: 'Clotrimazol AL 1% Crema Tópica',             category: 'antifungicos',    img: 'assects/Clotrimazol al 1%.png' },
  { id: 95, name: 'Clotrimazol Solución 1%',                     category: 'antifungicos',    img: 'assects/Clotrimazol Solucion 1.png' },
  { id: 96, name: 'Fluconazol Cápsulas BP 150 mg',              category: 'antifungicos',    img: 'assects/Fluconazol.png' },
  { id: 97, name: 'Itraconazole Tablets BP 10 mg',              category: 'antifungicos',    img: 'assects/Itraconazole.png' },
  { id: 98, name: 'Ketoconazol Tabletas USP 200 mg',            category: 'antifungicos',    img: 'assects/Ketoconazol 200 mg.png' },
  { id: 99, name: 'Ketoconazol AL 2% Crema Tópica',            category: 'antifungicos',    img: 'assects/Ketoconazol Al 2%.png' },

  // ── GASTROINTESTINAL ──
  { id: 100, name: 'Albendazole Suspensión Oral',               category: 'gastrointestinal', img: 'assects/Albendazol oral.png' },
  { id: 101, name: 'Loperamide Cápsulas BP 2 mg',              category: 'gastrointestinal', img: 'assects/Loperamide.png' },
  { id: 102, name: 'Metronidazol Tabletas USP 500 mg',         category: 'gastrointestinal', img: 'assects/Metronidazol.png' },
  { id: 103, name: 'Omeprazol 20 mg Cápsulas (LANSA)',         category: 'gastrointestinal', img: 'assects/Omeprazol.png' },
  { id: 104, name: 'Lansoprazol Cápsulas USP 30 mg',           category: 'gastrointestinal', img: 'assects/Lansoprazol.png' },
  { id: 105, name: 'Secnidazol Tabletas 1000 mg',              category: 'gastrointestinal', img: 'assects/Secnidazol.png' },

  // ── SISTEMA NERVIOSO ──
  { id: 106, name: 'Carbamazepina Tabletas 200 mg',            category: 'neurologico',      img: 'assects/Carbamazepina.png' },
  { id: 107, name: 'Clorpromazina Tabletas BP 100 mg',         category: 'neurologico',      img: 'assects/Clorpromazina.png' },
  { id: 108, name: 'Fluoxetina Cápsulas USP 20 mg',            category: 'neurologico',      img: 'assects/Fluoxetina.png' },
  { id: 109, name: 'Pregabalina Cápsulas 300 mg',              category: 'neurologico',      img: 'assects/Pregabalina.png' },

  // ── DERMATOLÓGICOS ──
  { id: 110, name: 'Aciclovir Crema 5%',                       category: 'dermatologico',    img: 'assects/Aciclovir Crema.png' },
  { id: 111, name: 'Gentamicina Crema BP 0.3% W/W',           category: 'dermatologico',    img: 'assects/Gentamicina crema.png' },
  { id: 112, name: 'Hidrocortisona Crema BP 1% W/W',          category: 'dermatologico',    img: 'assects/Hidrocortisona.png' },
  { id: 113, name: 'Crema Triple (Betametasona + Clotrimazol + Gentamicina)', category: 'dermatologico', img: 'assects/Triple crema.png' },
  // Archivo "Amlodipine Besylate 10mg.png" contiene Dexametasona
  { id: 114, name: 'Dexametasona Tabletas BP 0.5 mg',          category: 'dermatologico',    img: 'assects/Dexametasona.png' },

  // ── OTROS ──
  { id: 115, name: 'Acetazolamide Tablets BP 250 mg',          category: 'otros',            img: 'assects/Acetazolamide.png' },
  { id: 116, name: 'ASMOL-5 (Prednisona Tabletas USP 5 mg)',   category: 'otros',            img: 'assects/Asmol - 5.png' },
  { id: 117, name: 'ASMOL-50 (Prednisona Tabletas USP 50 mg)', category: 'otros',            img: 'assects/Asmol - 50.png' },
  { id: 118, name: 'Cetirizine Tablets BP 10 mg',              category: 'otros',            img: 'assects/Cetirizine.png' },
  { id: 119, name: 'Diphenhydramine Tablets BP 25 mg',         category: 'otros',            img: 'assects/Diphenhydramine.png' },
  { id: 120, name: 'Loratadina Tabletas 10 mg',                category: 'otros',            img: 'assects/Loratadina.png' },
  { id: 121, name: 'Tadalafila Tabletas USP 20 mg',            category: 'otros',            img: 'assects/Tadalafila.png' },
  { id: 122, name: 'VIVO (Sildenafil Citrato 100 mg)',         category: 'otros',            img: 'assects/Vivo Saad.png' },
  { id: 123, name: 'Ambroxol Jarabe 15 mg/5ml',               category: 'otros',            img: 'assects/Ambrozol Jarabe.png' },
  { id: 124, name: 'Ambroxol Tabletas 30 mg',                  category: 'otros',            img: 'assects/Ambrozol.png' },
  { id: 125, name: 'Metformina Tabletas 500 mg',               category: 'otros',            img: 'assects/Metformina.png' },
  { id: 126, name: 'Metformina Tabletas BP 850 mg',            category: 'otros',            img: 'assects/Metformina 850 mg.png' },
];
